routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('anggota', 'AnggotaController');

Route::resource('kategori', 'KategoriController');

Route::resource('buku', 'BukuController');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $table = 'kategori';
    protected $primaryKey = 'id';
    protected $fillable = ['nama','deskripsi'];
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kategori;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $dataKategori = Kategori::all();


        if($request->query('nama')){
            $dataKategori = Kategori::where('nama', request()->nama)->get();
        }

        return view('kategori.data-kategori', compact('dataKategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kategori.create-kategori');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kategori' => 'required|max:30',
            'deskripsi' => 'required|max:255',
            
        ]);
        Kategori::create([
            'nama' => $request->nama_kategori,
            'deskripsi' => $request->deskripsi,
            
        ]);
        
        return redirect()->route('kategori.index')->with('msg', 'Data anda telah diinputkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dataKategori = Kategori::find($id);
        return view('kategori.detail-kategori', compact('dataKategori'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dataKategori = Kategori::find($id);
        return view('kategori.edit-kategori',compact('dataKategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validasi = $request->validate([
            'nama_kategori' => 'required|max:30',
            'deskripsi' => 'required|max:255',
        ]);

        Kategori::whereId($id)->update($validasi);
        return redirect()->route('kategori.index')->with('msg', 'Data anda telah diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::findOrFail($id);
        $kategori->delete();
        return redirect()->route('kategori.index')->with('msg', 'Data anda telah dihapus!');
    }
}

resources/views/kategori/create-kategori.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
<div class="container">
        <div class="jumbotron">
            <h1 class="display-6">Tambah Data Kategori</h1>
            <hr class="my-4">
            <div class="card-body">
                    
                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>   
                    </div>
                @endif    

            <form action="{{ route('kategori.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="id">Nama Kategori</label>
                    <input type="text" class="form-control" name="nama_kategori" placeholder="Nama Kategori">
                </div>
                <div class="form-group">
                    <label for="nama">Deskripsi</label>
                    <input type="text" class="form-control" name="deskripsi" placeholder="Deskripsi Kategori Buku">
                </div>
                
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>
    </div>
@endsection

resources/views/kategori/data-kategori.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
    <div class="container">
        <div class="jumbotron">
                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>   
                    </div>
                @endif

                @php
                    $nama = ['Sosial', 'Biologi', 'Geografi', "SEMUA"];
                @endphp


            <h1 class="display-6">Data Kategori</h1>
            <hr class="my-2">     

            <a href="{{ route('kategori.create') }}" class="btn btn-primary mb-1 my-3">Tambah Kategori</a>
            <form action="{{route('kategori.index')}}" class="row mb-4">
                    <div class="col-md-8">
                        <select name="nama" class="form-control">
                            <option value="" disabled selected>Pilih Kategori</option>
                            @foreach ($nama as $ktgr)
                            <option value="{{ $ktgr == "SEMUA" ? "" : $ktgr }}" >{{ $ktgr }} </option>
                            @endforeach 
                        </select>
                    </div>
                    <input type="submit" class="btn btn-success float-right mb-4" value="Cari">

            <table class="table">
                <thead class="thead-dark">
                    <tr>
                
                    <th scope="col">Kategori Buku</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Action</th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($dataKategori as $kt)
                    <tr>
                        <td>{{ $kt['nama'] }}</td>
                        <td>{{ $kt['deskripsi'] }}</td>
                        <td>
                            <form action="{{ route('kategori.destroy',$kt['id']) }}" method="POST">
                            <a href="{{ route('kategori.show',$kt['id']) }}" class="badge badge-primary">Detail</a>
                            <a href="{{ route('kategori.edit',$kt['id']) }}" class="badge badge-primary">Edit</a>

                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="badge badge-danger" onclick="return confirm('Yakin ingin menghapus data?')">Hapus</button>
                        </form>
                        </td>
                    </tr>
                    @empty
                        <td colspan="3"> Tidak ada Data</td>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function action(){  
            var nama = document.getElementById('nama').value;
            window.location = "{{ url('kategori') }}/"+nama;
        }
    </script>
@endsection

resources/views/kategori/detail-kategori.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
    <div class="container">
        <div class="jumbotron">

            <h1 class="display-6">Detail Kategori</h1>
            <hr class="my-2">
            <button class="btn btn-danger float-left" onclick="history.go(-1)">Kembali</button>

            <div class="card-body">     

            <table class="table">
               @if($dataKategori)
                <tr>
                    <th style="border:0">Id Kategori</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataKategori['id'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Nama</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataKategori['nama'] }}</td>
                </tr>
                    <tr>
                    <th style="border:0">Alamat</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataKategori['deskripsi'] }}</td>
                </tr>
                
                @else
                    <td colspan="3">Tidak dapat menampilkan detail data</td>
                
                @endif
            </table>
        </div>
        </div>
    </div>
@endsection

resources/views/kategori/edit-kategori.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
<div class="container">
        <div class="jumbotron">
            <h1 class="display-6">Edit Data Kategori</h1>
            <hr class="my-4">
            <div class="card-body">

                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>   
                    </div>
                @endif

             @if ($dataKategori)
            <form action="{{ route('kategori.update', $dataKategori['id']) }}" method="POST">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="nama">Nama Kategori</label>
                    <input type="text" class="form-control" name="nama" placeholder="Nama Kategori" value="{{ $dataKategori['nama'] }}">
                </div>
                <div class="form-group">
                    <label for="alamat">Deskripsi</label>
                    <input type="text" class="form-control" name="deskripsi" placeholder="Deskripsi Kategori" value="{{ $dataKategori['deskripsi'] }}">
                </div>
                
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
            @else
                <p>Data tidak jelas, tidak dapat mengedit data</p>
            @endif
        </div>
    </div>
</div>
@endsection