routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('anggota', 'AnggotaController');

Route::resource('kategori', 'KategoriController');

Route::resource('buku', 'BukuController');

app/Buku.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
	protected $table = 'buku';
    protected $primaryKey = 'id';
    protected $fillable = ['judul','deskripsi','kategori','pengarang','tahun','stok','cover'];
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Buku;

class BukuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $dataBuku = Buku::all();


        if($request->query('judul')){
            $dataBuku = Buku::where('judul', request()->judul)->get();
        }

        return view('buku.data-buku', compact('dataBuku'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('buku.create-buku');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|max:50',
            'deskripsi' => 'required|max:255',
            'kategori' => 'required|max:30',
            'pengarang' => 'required|max:30',
            'tahun' => 'required|max:4',
            'stok' => 'required|max:3',
            'cover' => 'required|max:255',
         
        ]);
        Buku::create([
            'judul' => $request->judul,
            'deskripsi' => $request->deskripsi,
            'kategori' => $request->kategori,
            'pengarang' => $request->pengarang,
            'tahun' => $request->tahun,
            'stok' => $request->stok,
            'cover' => $request->cover,
        ]);
        
        return redirect()->route('buku.index')->with('msg', 'Data anda telah diinputkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dataBuku = Buku::find($id);
        return view('buku.detail-buku', compact('dataBuku'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dataBuku = Buku::find($id);
        return view('buku.edit-buku',compact('dataBuku'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required|max:50',
            'deskripsi' => 'required|max:255',
            'kategori' => 'required|max:30',
            'pengarang' => 'required|max:30',
            'tahun' => 'required|max:4',
            'stok' => 'required|max:3',
            'cover' => 'required|max:255',
         
        ]);

        Buku::whereId($id)->update($validasi);
        return redirect()->route('buku.index')->with('msg', 'Data anda telah diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $buku = Buku::findOrFail($id);
        $buku->delete();
        return redirect()->route('buku.index')->with('msg', 'Data anda telah dihapus!');
    }
}

resources/views/buku/create-buku.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
<div class="container">
        <div class="jumbotron">
            <h1 class="display-6">Tambah Data Buku</h1>
            <hr class="my-4">
            <div class="card-body">
                    
                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>   
                    </div>
                @endif    

            <form action="{{ route('buku.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="judul">Judul</label>
                    <input type="text" class="form-control" name="judul" placeholder="Judul Buku">
                </div>
                <div class="form-group">
                    <label for="penulis">Deskripsi</label>
                    <input type="text" class="form-control" name="deskripsi" placeholder="Deskripsi">
                </div>
                <div class="form-group">
                    <label for="penerbit">Kategori</label>
                    <input type="text" class="form-control" name="kategori" placeholder="Kategori">
                </div>
                <div class="form-group">
                    <label for="tahun_terbit">Penulis</label>
                    <input class="form-control" name="pengarang" placeholder="Penulis">
                </div>
                <div class="form-group">
                    <label for="kategori">Tahun</label>
                    <input type="text" class="form-control" name="tahun" placeholder="Tahun Terbit">
                </div>
                <div class="form-group">
                    <label for="kategori">Jumlah Buku</label>
                    <input type="text" class="form-control" name="stok" placeholder="Jumlah Buku">
                </div>
                <div class="form-group">
                    <label for="kategori">Cover Buku</label>
                    <input type="file" class="form-control" name="cover" placeholder="Cover Buku">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>
    </div>
@endsection

resources/views/buku/data-buku.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
    <div class="container">
        <div class="jumbotron">

            @php
                $judul = ['Codingan', 'Beuty Inside', "SEMUA"];
            @endphp


            @if ($msg = Session::get('msg'))
                <div class="alert alert-success">
                    <span>{{ $msg }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>   
                </div>
            @endif 

            <h1 class="display-6">Data Buku</h1>
            <hr class="my-2">     

            <a href="{{ route('buku.create') }}" class="btn btn-primary mb-1 my-3">Tambah Buku</a>
            <form action="{{route('buku.index')}}" class="row mb-4">
                    <div class="col-md-8">
                        <select name="nama" class="form-control">
                            <option value="" disabled selected>Pilih Judul Buku</option>
                            @foreach ($judul as $jdl)
                            <option value="{{ $jdl == "SEMUA" ? "" : $jdl }}" >{{ $jdl }} </option>
                            @endforeach 
                        </select>
                    </div>
                    <input type="submit" class="btn btn-success float-right mb-4" value="Cari">

            <table class="table">
                <thead class="thead-dark">
                    <tr>
                
                    <th scope="col">Judul Buku</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Penulis</th>
                    <th scope="col">Tahun Terbit</th>
                    <th scope="col">Jumlah Buku</th>
                    <th scope="col">Cover Buku</th>
                    <th scope="col">Action</th>
                    
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($dataBuku as $bk)
                    <tr>
                        <td>{{ $bk['judul'] }}</td>
                        <td>{{ $bk['deskripsi'] }}</td>
                        <td>{{ $bk['kategori'] }}</td>
                        <td>{{ $bk['pengarang'] }}</td>
                        <td>{{ $bk['tahun'] }}</td>
                        <td>{{ $bk['stok'] }}</td>
                        <td><img src='image/{{ $bk->cover }}' style='width:80px; height:100px;'></td>

                        <td>
                            <form action="{{ route('buku.destroy',$bk['id']) }}" method="POST">
                            <a href="{{ route('buku.show',$bk['id']) }}" class="badge badge-primary">Detail</a>
                            <a href="{{ route('buku.edit',$bk['id']) }}" class="badge badge-primary">Edit</a>
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="badge badge-danger" onclick="return confirm('Yakin ingin menghapus data?')">Hapus</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function action(){
            var judul = document.getElementById('judul').value;
            window.location.href = "{{ url('buku') }}/"+judul;
        }
    </script>
@endsection

resources/views/buku/detail-buku.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
    <div class="container">
        <div class="jumbotron">
        @if(session('msg'))
            <div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
                {{session('msg')}}

                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
            <h1 class="display-6">Detail Buku</h1>
            <hr class="my-2">
            <button class="btn btn-danger float-left" onclick="history.go(-1)">Kembali</button>     

            <table class="table">
                @if($dataBuku)
                <tr>
                    <th style="border:0">Judul</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataBuku['judul'] }}</td>
                </tr>
                    <tr>
                    <th style="border:0">Deskripsi</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataBuku['deskripsi'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Kategori</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataBuku['kategori'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Penulis</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataBuku['pengarang'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Tahun</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataBuku['tahun'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Jumlah Buku</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataBuku['stok'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Cover Buku</th>
                    <td style="border:0">:</td>
                    <td style="border:0"><img src='image/{{ $dataBuku->cover }}' style='width:80px; height:50px;'></td>
                </tr>
                 @else
                    <td colspan="3">Tidak dapat menampilkan detail data</td>
                
                @endif
            </table>
        </div>
    </div>
@endsection

resources/views/buku/edit-buku.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
<div class="container">
        <div class="jumbotron">
            <h1 class="display-6">Edit Data Buku</h1>
            <hr class="my-4">
            <div class="card-body">

             @if ($dataBuku)
            <form action="{{ route('buku.update', $dataBuku['id']) }}" method="POST">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="judul">Judul</label>
                    <input type="text" class="form-control" name="judul" placeholder="Judul Buku" value="{{ $dataBuku['judul'] }}">
                </div>
                <div class="form-group">
                    <label for="penulis">Deskripsi</label>
                    <input type="text" class="form-control" name="deskripsi" placeholder="Deskripsi" value="{{ $dataBuku['deskripsi'] }}">
                </div>
                <div class="form-group">
                    <label for="penerbit">Kategori</label>
                    <input type="text" class="form-control" name="kategori" placeholder="Kategori" value="{{ $dataBuku['kategori'] }}">
                </div>
                <div class="form-group">
                    <label for="tahun_terbit">Penulis</label>
                    <input class="form-control" name="pengarang" placeholder="Penulis" value="{{ $dataBuku['pengarang'] }}">
                </div>
                <div class="form-group">
                    <label for="kategori">Tahun</label>
                    <input type="text" class="form-control" name="tahun" placeholder="Tahun Terbit" value="{{ $dataBuku['tahun'] }}">
                </div>
                <div class="form-group">
                    <label for="kategori">Jumlah Buku</label>
                    <input type="text" class="form-control" name="stok" placeholder="Jumlah Buku" value="{{ $dataBuku['stok'] }}">
                </div>
                <div class="form-group">
                    <label for="kategori">Cover Buku</label>
                    <input type="file" class="form-control" name="cover" placeholder="Cover Buku" value="{{ $dataBuku['cover'] }}">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
            @else
                <p>Data tidak jelas, tidak dapat mengedit data</p>
            @endif
        </div>
    </div>
</div>
@endsection