routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('anggota', 'AnggotaController');

Route::resource('kategori', 'KategoriController');

Route::resource('buku', 'BukuController');

app/Anggota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anggota extends Model
{
    protected $table = 'anggota';
    protected $primaryKey = 'id';
    protected $fillable = ['nama','alamat','jk','email','nohp'];
}

app/Http/Controllers/AnggotaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Anggota;

class AnggotaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $dataAnggota = Anggota::all();


        if($request->query('alamat')){
            $dataAnggota = Anggota::where('alamat', request()->alamat)->get();
        }

        return view('anggota.data-anggota', compact('dataAnggota'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('anggota.create-anggota');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_anggota' => 'required|max:30',
            'alamat' => 'required|max:255',
            'email' => 'required|max:30|unique:anggota',
            'no_telp' => 'required|max:13',
        ]);
        Anggota::create([
            'nama' => $request->nama_anggota,
            'alamat' => $request->alamat,
            'jk' => $request->jenis_kelamin,
            'email' => $request->email,
            'nohp' => $request->no_telp,
        ]);
        
        return redirect()->route('anggota.index')->with('msg', 'Data anda telah diinputkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dataAnggota = Anggota::find($id);
        return view('anggota.detail-anggota', compact('dataAnggota'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $dataAnggota = Anggota::find($id);
        return view('anggota.edit-anggota',compact('dataAnggota'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validasi = $request->validate([
            'nama_anggota' => 'required|max:30',
            'alamat' => 'required|max:255',
            'email' => 'required|max:30|unique:anggota',
            'no_telp' => 'required|max:13',
        ]);

        Anggota::whereId($id)->update($validasi);
        return redirect()->route('anggota.index')->with('msg', 'Data anda telah diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $anggota = Anggota::findOrFail($id);
        $anggota->delete();
        return redirect()->route('anggota.index')->with('msg', 'Data anda telah dihapus!');
    }
}

resources/views/anggota/create-anggota.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
<div class="container">
        <div class="jumbotron">
            <h1 class="display-6">Tambah Data Anggota</h1>
            <hr class="my-4">
            <div class="card-body">
                    
                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>   
                    </div>
                @endif     

            <form action="{{ route('anggota.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="nama">Nama Anggota</label>
                    <input type="text" class="form-control" name="nama_anggota" placeholder="Nama Anggota">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="text" class="form-control" name="alamat" placeholder="Alamat Anggota">
                </div>
                <div class="form-group">
                    <label for="jenis_kelamin">Jenis Kelamin</label>
                    <select class="form-control" name="jenis_kelamin">
                        <option value="laki-laki">Laki-laki</option>
                        <option value="perempuan">Perempuan</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="email">Alamat Email</label>
                    <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="no_telp">No. HP</label>
                    <input type="text" class="form-control" name="no_telp" placeholder="NO. HP">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>
    </div>
@endsection

resources/views/anggota/data-anggota.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
    <div class="container">
        <div class="jumbotron">

            @php
                $alamat = ['Tegal', 'Slawi', 'Brebes', 'Pemalang', "SEMUA"];
            @endphp
                    
                

                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>   
                    </div>
                @endif


            <h1 class="display-6">Data Anggota</h1>
            <hr class="my-2">     

            <a href="{{ route('anggota.create') }}" class="btn btn-primary mb-1 my-3">Tambah Anggota</a>

            <form action="{{route('anggota.index')}}" class="row mb-4">
                    <div class="col-md-8">
                        <select name="alamat" class="form-control">
                            <option value="" disabled selected>Pilih Alamat</option>
                            @foreach ($alamat as $almt)
                            <option value="{{ $almt == "SEMUA" ? "" : $almt }}" >{{ $almt }} </option>
                            @endforeach 
                        </select>
                    </div>
                    <input type="submit" class="btn btn-success float-right mb-4" value="Cari">

            <table class="table">
                <thead class="thead-dark">
                    <tr>
                
                    <th scope="col">Nama</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Jenis Kelamin</th>
                    <th scope="col">Email</th>
                    <th scope="col">No. HP</th>
                    <th scope="col">Action</th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($dataAnggota as $ang)
                    <tr>
                        <td>{{ $ang['nama'] }}</td>
                        <td>{{ $ang['alamat'] }}</td>
                        <td>{{ $ang['jk'] }}</td>
                        <td>{{ $ang['email'] }}</td>
                        <td>{{ $ang['nohp'] }}</td>
                        <td>
                            <form action="{{ route('anggota.destroy',$ang['id']) }}" method="POST">
                            <a href="{{ route('anggota.show',$ang['id']) }}" class="badge badge-primary">Detail</a>
                            <a href="{{ route('anggota.edit',$ang['id']) }}" class="badge badge-primary">Edit</a>
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="badge badge-danger" onclick="return confirm('Yakin ingin menghapus data?')">Hapus</button>
                            </form>
                        </td>
                    </tr>
                    @empty
                        <td colspan="3"> Tidak ada Data</td>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function action(){  
            var alamat = document.getElementById('alamat').value;
            window.location = "{{ url('anggota') }}/"+alamat;
        }
    </script>
@endsection

resources/views/anggota/detail-anggota.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
    <div class="container">
        <div class="jumbotron">
        
            <h1 class="display-6">Detail Anggota</h1>
            <hr class="my-2">
            <button class="btn btn-danger float-left" onclick="history.go(-1)">Kembali</button>

            <div class="card-body">     

            <table class="table">
                @if($dataAnggota)
                <tr>
                    <th style="border:0">Id Anggota</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataAnggota['id'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Nama</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataAnggota['nama'] }}</td>
                </tr>
                    <tr>
                    <th style="border:0">Alamat</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataAnggota['alamat'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Jenis Kelamin</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataAnggota['jk'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">Email</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataAnggota['email'] }}</td>
                </tr>
                <tr>
                    <th style="border:0">No. Telp</th>
                    <td style="border:0">:</td>
                    <td style="border:0">{{ $dataAnggota['nohp'] }}</td>
                </tr>
                @else
                    <td colspan="3">Tidak dapat menampilkan detail data</td>
                
                @endif
            </table>
        </div>
    </div>
    </div>
@endsection

resources/views/anggota/edit-anggota.blade.php
@extends('main')

@section('title', 'Laravel - SI Perpustakaan')

@section('content')
<div class="container">
        <div class="jumbotron">
            <h1 class="display-6">Edit Data Anggota</h1>
            <hr class="my-4">
            <div class="card-body">

                @if ($msg = Session::get('msg'))
                    <div class="alert alert-success">
                        <span>{{ $msg }}</span>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>                        
                    </div>
                @endif

            
            @if ($dataAnggota)
            <form action="{{ route('anggota.update', $dataAnggota['id']) }}" method="POST">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="nama">Nama Anggota</label>
                    <input type="text" class="form-control" name="nama_anggota" placeholder="Nama Anggota" value="{{ $dataAnggota['nama'] }}">
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat</label>
                    <input type="text" class="form-control" name="alamat" placeholder="Alamat Anggota" value="{{ $dataAnggota['alamat'] }}">
                </div>
                <div class="form-group">
                    <label for="jenis_kelamin">Jenis Kelamin</label>
                    <select class="form-control" name="jenis_kelamin" value="{{ $dataAnggota['jk'] }}">
                        <option value="laki-laki">Laki-laki</option>
                        <option value="perempuan">Perempuan</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="email">Alamat Email</label>
                    <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email" value="{{ $dataAnggota['email'] }}">
                </div>
                <div class="form-group">
                    <label for="no_telp">No. HP</label>
                    <input type="text" class="form-control" name="no_telp" placeholder="NO. HP" value="{{ $dataAnggota['nohp'] }}">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
            @else
                <p>Data tidak jelas, tidak dapat mengedit data</p>
            @endif
        </div>
    </div>
</div>
@endsection